# This workflow will deploy the app to Render when commits are push
# to the 'main' branch of the repository

name: Render deployment

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - uses: gperdrizet/render-deploy@1.0.0
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'production'
          github_token: ${{ secrets.GITHUB_TOKEN }}