# This workflow will install Python dependencies and run tests when
# pull request is created to bring changes into main. Note: with a branch
# protection rule active, this test must pass for the merge to be possible

name: Pytest

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Test with Python 3.11
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
        
    - name: Install dependencies
      run: |
        python -m pip install -r deployment_requirements.txt

    - name: Test with pytest
      run: python -m pytest tests/test_model.py